### ISSUE TITLE
Ask: cache Zenhub epics with some refresh date

### ISSUE THREAD

**Issue by heaths** [AlexGhiondea/IssueCreator#7]
When starting the app, fetching Zenhub epics takes a while. It'd be nice if they were cached, perhaps with a timestamp we could use for staleness (like an If-Modified-Since - maybe Zenhub even supports that and we could just pass through).

Note: this may not be all that important, if not for bug #6 forcing me to restart often. If people only used this every few days, fetching a list makes more sense each time. Still, the conditional header check would even speed those scenarios up if there was no change, assuming Zenhub even supports that.

**Comment by AlexGhiondea** [comment]
@heaths the list of epics for the repo is cached here: https://github.com/AlexGhiondea/IssueCreator/blob/master/src/IssueCreator/IssueManager.cs#L230

Or you mean between app restarts?

**Comment by heaths** [comment]
Between app restarts, yes.

**Comment by AlexGhiondea** [comment]
I wonder if I can simply replace the memory cache I have with something that stores stuff on disk... might be doable and rather cheap.
